<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-ios</TargetFramework>
    <OutputType>Exe</OutputType>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
    <ApplicationTitle>PortBridge</ApplicationTitle>
    <ApplicationId>org.portbridge.app</ApplicationId>
    <ApplicationDisplayVersion>1.5.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PortBridge.Core\PortBridge.Core.csproj" />
    <MauiIcon Include="Resources\AppIcon\appicon.svg" />
  </ItemGroup>
</Project>
